"""Emit a drop-in Godot 4 folder from a normalised variant set.

Output folder structure:
    <root>/bananadot_<component_type>/
        assets/
            normal.png
            hover.png
            pressed.png
            disabled.png
        example.tscn        # TextureButton wired to the assets
        README.md           # "drop into res:// and open example.tscn"

Why TextureButton over a full Theme resource for v1:
  - Drops in with zero extra import steps — user unzips, opens example.tscn,
    it works. A Theme with StyleBoxTexture + 9-slice needs import-time
    config to look right.
  - TextureButton's state-texture properties (texture_normal / _hover /
    _pressed / _disabled) map 1:1 to what we generated.
  - Theme is the right answer once we add scalable (9-slice) panels. Until
    then it's ceremony without payoff.

Path convention:
    example.tscn references assets by `res://bananadot_<component_type>/assets/...`.
    The user must unzip into their project root for paths to resolve. README
    explains this and the find-and-replace escape hatch if they rename.
"""

from __future__ import annotations

import io
import shutil
from pathlib import Path

from PIL import Image


# Order matters for readability of the generated .tscn; keep canonical states first.
BUTTON_STATE_TO_PROP = {
    "normal": "texture_normal",
    "pressed": "texture_pressed",
    "hover": "texture_hover",
    "disabled": "texture_disabled",
}


def emit_component(
    component_type: str,
    variants: dict[str, bytes],
    root: Path,
    source_png: bytes | None = None,
) -> Path:
    """Write the Godot bundle to disk; return the folder path.

    `source_png` is optional and only used to decide whether to set
    `texture_filter = nearest` (pixel-art inputs look awful with linear
    filtering).
    """
    if component_type != "button":
        raise NotImplementedError(
            f"Only 'button' is wired for v1. Add a template for {component_type!r} "
            "alongside BUTTON_STATE_TO_PROP when needed."
        )

    folder_name = f"bananadot_{component_type}"
    out_dir = Path(root) / folder_name
    assets_dir = out_dir / "assets"

    # Start clean — stale files from a previous run would ride along in the zip.
    if out_dir.exists():
        shutil.rmtree(out_dir)
    assets_dir.mkdir(parents=True, exist_ok=True)

    # Write every variant we have; skip states the template doesn't reference.
    written: dict[str, Path] = {}
    for state, png_bytes in variants.items():
        if state not in BUTTON_STATE_TO_PROP:
            continue
        path = assets_dir / f"{state}.png"
        path.write_bytes(png_bytes)
        written[state] = path

    if "normal" not in written:
        raise RuntimeError("Pipeline produced no 'normal' variant — refusing to emit bundle.")

    pixel_art = _looks_like_pixel_art_bytes(source_png) if source_png else False

    (out_dir / "example.tscn").write_text(
        _render_tscn(folder_name=folder_name, states=list(written), pixel_art=pixel_art),
        encoding="utf-8",
    )
    (out_dir / "README.md").write_text(
        _render_readme(folder_name=folder_name, component_type=component_type),
        encoding="utf-8",
    )

    return out_dir


# --- templates ----------------------------------------------------------------


def _render_tscn(*, folder_name: str, states: list[str], pixel_art: bool) -> str:
    """Godot 4 scene file with a TextureButton wired to the generated textures."""
    # ExtResource ids must be unique strings inside the file. We use `<n>_<state>`.
    ext_lines: list[str] = []
    prop_lines: list[str] = []
    # Canonical ordering for determinism.
    ordered = [s for s in BUTTON_STATE_TO_PROP if s in states]

    for i, state in enumerate(ordered, start=1):
        ext_id = f"{i}_{state}"
        ext_lines.append(
            f'[ext_resource type="Texture2D" '
            f'path="res://{folder_name}/assets/{state}.png" id="{ext_id}"]'
        )
        prop_lines.append(f'{BUTTON_STATE_TO_PROP[state]} = ExtResource("{ext_id}")')

    load_steps = len(ordered) + 2  # ext resources + node + scene header
    # texture_filter: 0 = inherit, 1 = nearest, 2 = linear. We only pin to nearest
    # for detected pixel art; everything else inherits the project default.
    filter_line = "texture_filter = 1\n" if pixel_art else ""

    return (
        f"[gd_scene load_steps={load_steps} format=3]\n\n"
        + "\n".join(ext_lines)
        + "\n\n"
        + '[node name="Demo" type="TextureButton"]\n'
        + filter_line
        + "\n".join(prop_lines)
        + "\n"
    )


def _render_readme(*, folder_name: str, component_type: str) -> str:
    return f"""# bananadot {component_type}

Generated by bananadot from a single source image.

## Install

Drop this **entire folder** into your Godot 4 project's root so it lives at:

```
res://{folder_name}/
```

Open `example.tscn` — you should see the {component_type} working
(hover / press / disabled states all wired up).

## Use in your own scenes

Option A — instance `example.tscn` as a `PackedScene`.

Option B — add a `TextureButton` node and point its texture properties at
the files in `assets/`:

- `texture_normal` → `assets/normal.png`
- `texture_pressed` → `assets/pressed.png`
- `texture_hover` → `assets/hover.png`
- `texture_disabled` → `assets/disabled.png`

## Renaming the folder

If you rename `{folder_name}`, search-and-replace the old path inside
`example.tscn` with the new one.
"""


# --- helpers ------------------------------------------------------------------


def _looks_like_pixel_art_bytes(png: bytes) -> bool:
    """Same heuristic cleanup.py uses — duplicated here to keep modules independent."""
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    if img.width > 128 or img.height > 128:
        return False
    colors = img.getcolors(maxcolors=65)
    return colors is not None and len(colors) <= 64
